os:
    - osx
    - linux
    - windows
language: node_js
node_js:
    - node
    - 14
    - 13
    - 12
    - 11
    - 10
cache: cargo
before_install:
    # Install Rust and Cargo
    - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
    - sh /tmp/rustup.sh -y
    - |
        if [ $TRAVIS_OS_NAME == 'linux' ]; then
            sudo apt install libxdo-dev;
        fi
    - export PATH="$HOME/.cargo/bin:$PATH"
    - |
        if [ $TRAVIS_OS_NAME == 'osx' ] || [ $TRAVIS_OS_NAME == 'linux' ]; then
            source "$HOME/.cargo/env";
        fi
    # Install NPM packages
    - node -v
    - npm -v
    - npm install
script:
    # Publish when using '[publish binary]' keywords
    - COMMIT_MESSAGE=$(git log --format=%B --no-merges -n 1 | tr -d '\n')
    - if [[ ${COMMIT_MESSAGE} =~ "[publish binary]" ]]; then npm run upload-binary || exit 0; fi;
